import type { TechNode } from '../core/types.js';

export const TECH_TREE: TechNode[] = [
  {
    id: 'irrigation',
    name: '灌溉技术',
    description: '开凿水渠引水灌溉，提高农田产量',
    prerequisites: [],
    requiredSkill: 'farming',
    requiredSkillLevel: 30,
    difficulty: 200,
    materials: [{ itemId: 'stone', quantity: 10 }, { itemId: 'wood', quantity: 5 }],
    unlocks: ['farmland_efficiency_20'],
    effects: [{ type: 'farmland_yield', value: 1.2 }],
  },
  {
    id: 'crop_rotation',
    name: '轮作技术',
    description: '通过轮作保持土壤肥力，防止地力衰退',
    prerequisites: ['irrigation'],
    requiredSkill: 'farming',
    requiredSkillLevel: 40,
    difficulty: 250,
    materials: [{ itemId: 'stone', quantity: 5 }],
    unlocks: ['fertility_preservation'],
    effects: [{ type: 'fertility_decay', value: 0.5 }],
  },
  {
    id: 'basic_metallurgy',
    name: '基础冶金',
    description: '改进熔炼技术，能打造更坚固的铁制工具',
    prerequisites: [],
    requiredSkill: 'blacksmithing',
    requiredSkillLevel: 40,
    difficulty: 300,
    materials: [{ itemId: 'iron', quantity: 8 }, { itemId: 'stone', quantity: 10 }],
    unlocks: ['iron_tools'],
    effects: [{ type: 'tool_quality', value: 1.3 }],
  },
  {
    id: 'weaving_loom',
    name: '纺织机',
    description: '改进织布机，大幅提高布匹产量',
    prerequisites: [],
    requiredSkill: 'weaving',
    requiredSkillLevel: 35,
    difficulty: 200,
    materials: [{ itemId: 'wood', quantity: 8 }],
    unlocks: ['cloth_production_30'],
    effects: [{ type: 'weaving_output', value: 1.3 }],
  },
  {
    id: 'papermaking',
    name: '造纸术',
    description: '用树皮和麻头造纸，方便记录和存档',
    prerequisites: [],
    requiredSkill: 'literacy',
    requiredSkillLevel: 30,
    difficulty: 150,
    materials: [{ itemId: 'wood', quantity: 5 }, { itemId: 'cloth', quantity: 2 }],
    unlocks: ['record_keeping'],
    effects: [{ type: 'archive_capacity', value: 2 }],
  },
  {
    id: 'pottery_kiln',
    name: '陶窑',
    description: '改进烧窑技术，能批量生产精美陶器',
    prerequisites: ['papermaking'],
    requiredSkill: 'fortune-telling',
    requiredSkillLevel: 25,
    difficulty: 180,
    materials: [{ itemId: 'stone', quantity: 8 }, { itemId: 'wood', quantity: 5 }],
    unlocks: ['pottery_production'],
    effects: [{ type: 'pottery_output', value: 1.5 }],
  },
  {
    id: 'basic_medicine',
    name: '基础医学',
    description: '总结常见疾病治疗经验，建立基础医疗体系',
    prerequisites: [],
    requiredSkill: 'medicine',
    requiredSkillLevel: 30,
    difficulty: 200,
    materials: [{ itemId: 'herbal_medicine', quantity: 3 }],
    unlocks: ['herbal_remedies'],
    effects: [{ type: 'health_recovery', value: 1.2 }],
  },
  {
    id: 'sailing',
    name: '造船术',
    description: '改进渔船设计，能到更远的水域捕鱼',
    prerequisites: [],
    requiredSkill: 'boat-building',
    requiredSkillLevel: 40,
    difficulty: 250,
    materials: [{ itemId: 'wood', quantity: 10 }],
    unlocks: ['fishing_boost'],
    effects: [{ type: 'fishing_output', value: 1.2 }],
  },
];
